services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: flyrank
      POSTGRES_PASSWORD: flyrank
      POSTGRES_DB: flyrank_be04
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pgdata: